# Use official Node.js 20 Alpine image
FROM node:20

# Dépendances nécessaires pour la compilation des modules natifs comme bcrypt
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    pixman-dev \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    giflib-dev

# Set working directory (recommandé, même si ce n'est pas strictement nécessaire)
WORKDIR /app

# Copie les fichiers de package.json pour une meilleure mise en cache des couches
COPY package*.json ./

# Installation des dépendances (forcera la recompilation des modules natifs comme bcrypt)
RUN npm install --build-from-source

# Copie tous les fichiers de l'application
COPY . .

# Expose le port sur lequel ton app écoute
EXPOSE 8070

# Lancer l'application
CMD ["node", "server.js"]
