version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistance des données

  app:
    build: .
    image: 192.168.65.129:8083/backend:6.0
    restart: always
    container_name: back
    ports:
      - "8070:8070"
    environment:
      MONGODB_URI: "mongodb://root:example@db:27017/hrms?authSource=admin"
    depends_on:
      - db

volumes:
  mongo-data:
