# Utiliser une image Node.js 20 basée sur Alpine
FROM node:20-alpine

# Installer les dépendances nécessaires pour la compilation des modules natifs comme bcrypt
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    giflib-dev \
    librsvg-dev \
    && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de package.json pour une meilleure mise en cache des couches
COPY package*.json ./

# Installation des dépendances (forcera la recompilation des modules natifs comme bcrypt)
RUN npm install --build-from-source
RUN npm rebuild canvas --build-from-source

# Copier tous les fichiers de l'application
COPY . .

# Exposer le port sur lequel ton app écoute
EXPOSE 8070

# Lancer l'application
CMD ["node", "server.js"]
